spring:
  application:
    name: Spring-OAuth2ResourceServerExample
  config:
    import: file:.env.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.wfis.lol/application/o/zti-sem-public/
          jwk-set-uri: https://auth.wfis.lol/application/o/zti-sem-public/jwks/
      client:
        provider:
          authentik:
            authorization-uri: https://auth.wfis.lol/application/o/authorize/
            token-uri: https://auth.wfis.lol/application/o/token/
            user-info-uri: https://auth.wfis.lol/application/o/userinfo/
            user-name-attribute: sub
            jwk-set-uri: https://auth.wfis.lol/application/o/zti-sem-credentials/jwks/
springdoc:
    swagger-ui:
      oauth:
        use-pkce-with-authorization-code-grant: true
        scopes: openid,profile,email


